import esbuild from "esbuild";
import process from "process";

const prod = process.argv[2] === "--production";

const context = await esbuild.context({
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    "datacore"
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  jsx: "transform",
  jsxFactory: "dc.jsx",
  jsxFragment: "dc.Fragment",
  loader: {
    '.jsx': 'jsx',
    '.js': 'jsx'
  },
  define: {
    'process.env.NODE_ENV': prod ? '"production"' : '"development"'
  },
  splitting: false,
  keepNames: false,
  drop: prod ? ['console', 'debugger'] : [],
  banner: {
    js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/`
  }
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
  console.log("👀 Watching for changes...");
}